apiVersion: nais.io/v1alpha1
kind: Application

metadata:
  labels:
    team: designsystem
  name: golden-path-anniken
  namespace: designsystem

spec:
  ingresses:
    - https://golden-path-anniken.intern.dev.nav.no
  image: {{image}}
  port: 3000
  idporten:
    enabled: true
    sidecar:
      enabled: true
      autoLogin: true
  accessPolicy:
    outbound:
      rules:
        - application: frontend-golden-path-api
        - application: nav-dekoratoren
          namespace: personbruker