import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from "next/script";
import { fetchDecoratorReact } from "@navikt/nav-dekoratoren-moduler/ssr";
import { Page } from "@navikt/ds-react";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = async ({
  children,
}: Readonly<{ children: React.ReactNode }>) => {
  const Decorator = await fetchDecoratorReact({
    env: "prod",
  });

  return (
    <html lang="no">
      <head>
        <Decorator.HeadAssets />
      </head>
      <body>
        <Page footer={<Decorator.Footer />}>
          <Decorator.Header />
          {children}
          <Decorator.Scripts loader={Script} />
        </Page>
      </body>
    </html>
  );
};

export default RootLayout;
